# Example config of a Gree climate component with a current temperature sensor
substitutions:
  name: "gree-climate-with-sensor"

esphome:
  name: "${name}"
  platform: ESP8266
  board: d1_mini
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret ip_my_static_ip
    gateway: !secret ip_gateway
    subnet: !secret ip_subnet
  ap: 
    ssid: ${name}-AP
    password: !secret wifi_password
    ap_timeout: 3min
    
captive_portal:

logger:

api:

ota:
 
external_components:
  - source: local_components
    components: [ gree ]

sensor:
  - platform: homeassistant
    id: current_temperature
    name: "Current Temperature"
    entity_id: sensor.shawinigan_temperature
    state_class: measurement
    device_class: temperature
    accuracy_decimals: 1
    unit_of_measurement: 째C

climate:
- platform: gree
  name: "HVAC Head with sensor"
  pin: GPIO4
  visual:
    min_temperature: 10 째C
    max_temperature: 30 째C
    temperature_step: 1.0 째C
  sensor: current_temperature
